test_that("Looney Pyramid jackets", {
	skip_if_not(cache_has("HomeworldsBoxFront.jpg"))
	skip_if_not(cache_has("HomeworldsBoxBack.jpg"))
	f <- sbgj_homeworlds()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("IceDuoBoxFront.jpg"))
	skip_if_not(cache_has("IceDuoBoxBack.jpg"))
	f <- sbgj_ice_duo()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("JinxxFlatBoxFront.png"))
	skip_if_not(cache_has("JinxxFlatBoxBack.png"))
	f <- sbgj_jinxx()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("MartianChessBoxBack.jpg"))
	skip_if_not(cache_has("MartianChessBoxFront.jpg"))
	skip_if_not(cache_has("MartianChessSilverFlatBoxBack.png"))
	f <- sbgj_martian_chess()
	expect_true(file.exists(f))
	unlink(f)
	f <- sbgj_martian_chess(silver = TRUE)
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("NomidsBoxBack.jpg"))
	skip_if_not(cache_has("NomidsBoxFront.jpg"))
	f <- sbgj_nomids()
	expect_true(file.exists(f))
	unlink(f)
	skip_if_not(cache_has("NomidsLogo_Background.jpg"))
	skip_if_not(cache_has("Nomids_Rules6.pdf"))
	skip_if_not(cache_has("PyramidArcadeZoomBackground.jpg"))
	f <- sbgj_nomids(custom = TRUE)
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("LP4TopHeader.png"))
	skip_if_not(cache_has("Pyramids_Intro_Pamphlet7.pdf"))
	for (badge in unlist(pyramid_badges())) {
		filename <- str_glue("{badge}.png")
		skip_if_not(cache_has(filename))
	}
	f <- sbgj_looney_pyramids()
	expect_true(file.exists(f))
	unlink(f)
})
