test_that("Storage jackets", {
	skip_if_not(has_runtime_dependencies())
	skip_if_not(cache_has("dice.jpg"))
	f <- sbgj_dice(instructions = TRUE)
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("slate_black_stones.jpg"))
	skip_if_not(cache_has("yunzi_go_stones.jpg"))
	f <- sbgj_black_stones()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("glass_stones.jpg"))
	f <- sbgj_glass_stones()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("marbles_front.jpg"))
	skip_if_not(cache_has("marbles_back.jpg"))
	f <- sbgj_marbles()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("wooden_pawns.jpg"))
	f <- sbgj_pawns()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("polyhedral_dice.jpg"))
	f <- sbgj_polyhedral_dice()
	expect_true(file.exists(f))
	unlink(f)

	skip_if_not(cache_has("shell_white_stones.jpg"))
	skip_if_not(cache_has("yunzi_go_stones.jpg"))
	f <- sbgj_white_stones()
	expect_true(file.exists(f))
	unlink(f)
})
